import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/fish"

[selection]
save_to_clipboard = true

[window]
padding.x = 0
padding.y = 0
dynamic_padding = false

[font]
normal = { family = "Source Code Pro", style="Regular" }
