[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/fish"

[selection]
save_to_clipboard = true

[window]
padding.x = 0
padding.y = 0
dynamic_padding = false

[font]
normal = { family = "Hack Nerd Font"}
size = 10
